### ISSUE TITLE
Firehose and caching for event and match TBA data

### ISSUE THREAD

**Issue by brendanburkhart** [Pigmice2733/peregrine-backend#102]
Right now almost every request involving matches requires a roundtrip request to TBA, there should be a time period (several hours probably) where the server will just respond with the data it already has, and during that period the data is updated via the TBA firehose.

**Comment by fharding1** [comment]
Not looking forward to this haha. But it should probably get done.

**Comment by fharding1** [comment]
I don't think this needs to happen, what we have now is fine.
