### ISSUE TITLE
Event teams list should include teams that are in matches, but not on the TBA match list

### ISSUE THREAD

**Issue by calebeby** [Pigmice2733/peregrine-backend#118]
For example, Madtown Throwdown has many teams that bring multiple robots, where the extra/practice robots get their team numbers prefixed with `9` or `8`. So the team list route should return a combination of the teams list from TBA + the teams that are in matches

**Comment by brendanburkhart** [comment]
Fixed by https://github.com/Pigmice2733/peregrine-backend/pull/202 and https://github.com/Pigmice2733/peregrine-backend/pull/201
