### ISSUE TITLE
Authentication and user management

### ISSUE THREAD

**Issue by calebeby** [Pigmice2733/peregrine-backend#32]
I put these together because I thought they should go together because stars is an easy feature dependent on users.

https://github.com/Pigmice2733/peregrine-frontend/blob/dev/docs/docs.md#authenticate
https://github.com/Pigmice2733/peregrine-frontend/blob/dev/docs/docs.md#usersuserid
https://github.com/Pigmice2733/peregrine-frontend/blob/dev/docs/docs.md#users

**Comment by calebeby** [comment]
@fharding1 what still needs to be done here?

**Comment by fharding1** [comment]
https://github.com/Pigmice2733/peregrine-frontend/blob/dev/docs/docs.md#usersuseridstars
https://github.com/Pigmice2733/peregrine-frontend/blob/dev/docs/docs.md#usersuserid

**Comment by fharding1** [comment]
Right now the _only_ user-related endpoints are `/authenticate` and POST `/users`.
