### ISSUE TITLE
Couple `server` and `store` types

### ISSUE THREAD

**Issue by fharding1** [Pigmice2733/peregrine-backend#53]
IMO it makes more sense to just define `json` tags on `store` types than have the types defined in two places. What do you think @brendanburkhart

**Comment by brendanburkhart** [comment]
I'm down for whatever, but normally *decoupled* layers is the goal. In some ways it's cleaner to have just the store models, only have to change stuff in one place etc. buuut also then if one model needs to be different (the events model changes between `/events` and `/events/{eventKey}/info` for example) it's a little weird. Ultimately I think either way is fine.

**Comment by fharding1** [comment]
To me, since the whole concept of REST is that your API represents resources, it makes sense for them to be coupled. I think the frontend should comply to the backend being uber RESTful rather than have the backend do weird stuff to make frontend stuff nicer.

@calebeby
