### ISSUE TITLE
Middleware for eventKey, matchKey, etc, etc.

### ISSUE THREAD

**Issue by fharding1** [Pigmice2733/peregrine-backend#90]
So either:
- We have a middleware that looks in `mux.Vars` for `eventKey`, `matchKey`, bla, bla, bla to update events, matches, bla, bla, bla.
- We have a middleware where we specify dependencies on each route like `ihttp.Update(fooHandler, ihttp.Deps{Events: true, Matches: false, Teams: true})` to update events, matches, bla, bla, bla.

**Comment by fharding1** [comment]
I'm tagging this with good first issue, but I'm thinking whoever new works on this will need some help.

@NathanJesudason @VictorHuynh @j10k11 @AccordingtoProphecy would any of you be interested in working on this? If so, assign yourself.

**Comment by AccordingtoProphecy** [comment]
Not sure yet, though I could take it if no one else will. Is there a
deadline?

**Comment by fharding1** [comment]
Looks like Nathan already self-assigned himself so I think he's gonna be taking this one @AccordingtoProphecy. I'll assign you to the next good first issue that comes up, though.

**Comment by AccordingtoProphecy** [comment]
Thanks that's fine. I'm just super busy nowadays but I could try and fit
them in
