### ISSUE TITLE
Add context to ErrNoResults returns

### ISSUE THREAD

**Issue by fharding1** [Pigmice2733/peregrine-backend#94]
We should be providing context when we return ErrNoResults (that's the whole point of it being a type rather than just an error value), like this: https://github.com/Pigmice2733/peregrine-backend/blob/675f40c96bedb15565c08a7a3c8798eba0220b4b/internal/store/events.go#L65

But we aren't doing that everywhere: 

- https://github.com/Pigmice2733/peregrine-backend/blob/675f40c96bedb15565c08a7a3c8798eba0220b4b/internal/store/events.go#L82
- https://github.com/Pigmice2733/peregrine-backend/blob/675f40c96bedb15565c08a7a3c8798eba0220b4b/internal/store/matches.go#L75
- search all files for `ErrNoResults(` for more.

**Comment by NathanJesudason** [comment]
I could potentially work on this tomorrow
